services:
  postgres:
    image: postgres:16-alpine
    container_name: rpg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rpg_user
      POSTGRES_PASSWORD: rpg_pass
      POSTGRES_DB: rpg_online
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: